parser: babel-eslint
plugins: [flowtype]
extends: [eslint:recommended, plugin:flowtype/recommended]
env: {node: true, es6: true}
rules:
  array-bracket-spacing: [warn, never]
  arrow-body-style: [warn, as-needed]
  # arrow-parens: [warn, as-needed]
  arrow-spacing: warn
  block-spacing: [warn, always]
  brace-style: [warn, stroustrup, {allowSingleLine: true}]
  comma-dangle: [warn, always-multiline]
  comma-spacing: warn
  comma-style: warn
  # complexity: [error, 15]
  computed-property-spacing: warn
  dot-location: [warn, property]
  dot-notation: warn
  eol-last: error
  generator-star-spacing: [warn, before]
  indent: [warn, 2, {MemberExpression: off}]
  key-spacing: [warn, {mode: minimum}]
  keyword-spacing: warn
  linebreak-style: error
  # max-depth: [error, 5]
  max-len: [error, 80, 4]
  # max-statements: [error, 15]
  new-cap: warn
  no-caller: error
  no-console: off
  no-empty: off
  no-extra-parens: warn
  no-invalid-this: error
  no-labels: error
  no-lone-blocks: error
  no-multiple-empty-lines: warn
  no-restricted-syntax: [error, SwitchStatement, ForStatement, ForInStatement]
  no-self-compare: error
  no-sequences: error
  no-spaced-func: error
  no-throw-literal: error
  no-underscore-dangle: error
  no-unmodified-loop-condition: error
  no-unused-expressions: [error, {allowShortCircuit: true, allowTernary: true}]
  no-use-before-define: [error, {functions: false}]
  no-useless-concat: error
  no-useless-escape: error
  no-var: error
  no-void: error
  no-warning-comments: warn
  no-whitespace-before-property: warn
  no-with: error
  object-curly-spacing: [warn, never]
  object-shorthand: error
  operator-assignment: [error, always]
  operator-linebreak: [warn, before, {overrides: {=: ignore}}]
  prefer-arrow-callback: error
  prefer-const: error
  rest-spread-spacing: warn
  quotes: [warn, single, {avoidEscape: true, allowTemplateLiterals: true}]
  semi: [error, never]
  semi-spacing: warn
  space-before-blocks: warn
  space-before-function-paren: [warn, {anonymous: always, named: never}]
  # space-infix-ops: [warn, {int32Hint: true}]
  space-in-parens: warn
  space-unary-ops: warn
  template-curly-spacing: warn
  valid-jsdoc: warn
  yield-star-spacing: warn
  yoda: [warn, never]
  flowtype/space-after-type-colon: [warn, always, {allowLineBreak: true}]
